---
- name: Copy mysql-community.repo file
  template:
    src: "mysql-community.repo.j2"
    dest: "/etc/yum.repos.d/mysql-community.repo"
    owner: root
    group: root
    mode: 0644
  register: mysql_community_repo_output
  when: mysql_daemon.startswith('mysql')

- name: Copy mariadb.repo file
  template:
    src: "mariadb.repo.j2"
    dest: "/etc/yum.repos.d/mariadb.repo"
    owner: root
    group: root
    mode: 0644
  register: mysql_community_repo_output
  when: mysql_daemon == 'mariadb'

- name: Clean YUM repos metadata cache
  ansible.builtin.command: yum clean metadata
  when: mysql_community_repo_output.changed

- name: Ensure MySQL packages are installed.
  ansible.builtin.yum:
    name: "{{ mysql_packages }}"
    state: present
    enablerepo: "{{ mysql_enablerepo | default(omit, true) }}"
  register: rh_mysql_install_packages
