---
- name: Copy mysql-community.repo file
  template:
    src: "mysql-community.repo.j2"
    dest: "/etc/yum.repos.d/mysql-community.repo"
    owner: root
    group: root
    mode: 0644
  register: mysql_community_repo_output

- name: Clean YUM repos metadata cache
  command: yum clean metadata
  args:
    warn: false
  when: mysql_community_repo_output.changed

- name: Ensure MySQL packages are installed.
  yum:
    name: "{{ mysql_packages }}"
    state: present
    enablerepo: "{{ mysql_enablerepo | default(omit, true) }}"
  register: rh_mysql_install_packages
